# Generated by Django 2.2 on 2020-11-25 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='data de cadastro no Sistema')),
                ('update_at', models.DateTimeField(auto_now=True, null=True, verbose_name='data de atualização no Sistema')),
                ('name', models.CharField(max_length=50)),
                ('endpoint', models.CharField(max_length=50, unique=True)),
                ('logo_url', models.CharField(max_length=200)),
                ('about_us', models.TextField()),
                ('terms', models.TextField()),
                ('lgpd_terms', models.TextField()),
            ],
            options={
                'verbose_name': 'Configuração Geral',
                'verbose_name_plural': 'Configuraçãos Geral',
            },
        ),
    ]
