# Generated by Django 2.2 on 2020-11-25 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='about_us',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='config',
            name='lgpd_terms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='config',
            name='logo_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='config',
            name='terms',
            field=models.TextField(blank=True, null=True),
        ),
    ]
