# Generated by Django 2.2 on 2020-11-25 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_auto_20201125_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
