# Generated by Django 2.2 on 2020-11-25 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_config_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config',
            name='active',
        ),
    ]
