# Generated by Django 2.2.16 on 2020-12-08 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_remove_config_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='febre_number',
            field=models.FloatField(default=38),
        ),
    ]
