# Generated by Django 2.2 on 2020-12-14 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_remove_config_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='token',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='config',
            name='endpoint',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
