# Generated by Django 2.2 on 2020-12-14 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0005_config_febre_number'),
        ('config', '0005_auto_20201214_0221'),
    ]

    operations = [
    ]
